### ISSUE TITLE
Erro - Captcha

### ISSUE THREAD

**Issue by KarlmerABC** [urbanogilson/SICAR#3]
Hi, Gilson.

I hope you're well.
Great package for data extraction. It has helped me a lot in my doctorate.
It has been a few days since the captchar has been found. Did you notice this error? Since the changes you made, this error has appeared to me.

![image](https://user-images.githubusercontent.com/54607354/131340688-7c5621ec-f7bd-426d-889b-754199d57f22.png)

**Comment by urbanogilson** [comment]
Hello, Great to know the package is helping you.

I downgraded dependencies to avoid conflicts in Google Colab and tested the package on Google Colab and on my computer running Ubuntu 20.04.3 LTS through WSL 2.

You can try again on Colab if you are using it, otherwise I recommend you to uninstall the package from your personal computer and reinstall before using it.

If the error persists, let me know and provide as much detail as you can, so I can try to fix it as soon as possible.

Tests on Colab:

![image](https://user-images.githubusercontent.com/16805527/131365787-11215b30-d7ed-4fd0-8dae-295d0046e2d0.png)

![image](https://user-images.githubusercontent.com/16805527/131365715-5f475072-4f30-475d-b233-3d6d11837d69.png)

**Comment by KarlmerABC** [comment]
Hi.
I tested it again and it worked. 
Thanks.
